### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: D:\...

### ISSUE THREAD

**Issue by chunfengshiliburuni** [bgavran/AMDS_FER#1]
Hi！I want to know that I need to run which one(.py) to get the database.Another,when I  run the main.py ,I got this error : tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: D:\...
Can you help me please?

**Comment by Poi-kid** [comment]
I met this issue, too.
help!

**Comment by Poi-kid** [comment]
我猜这是天朝程序员才会有的问题。。。
刚刚替换了报错中的含有中文的路径为英文路径。。
问题就解决了。。。。。

**Comment by THUzhangga** [comment]
然而我并不带中文也出错...

**Comment by kennyyuen** [comment]
I got the same problem. Did you guys have a solution to this issue?

**Comment by bgavran** [comment]
Thanks for the bug reports! 
The problem stems from paths that have a mix of forward and backward slashes in them.
I tried to use os.path.join for most OS-related path merges but apparently I missed some of them in the code

**Comment by NgWilli** [comment]
中文路径会有问题，另外带转义的也可能会有问题，建议放根目录看一下

**Comment by bgavran** [comment]
I fixed the path problems on windows, things should work now

**Comment by yushuxin1** [comment]
I am also the problem. Who of you solved it?
